Projekat_Hotel/Controllers/Admin/AlatiController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projekat_Hotel.Models;

namespace Projekat_Hotel.Controllers.Admin
{
    [Authorize(Roles ="Admin")]
    public class AlatiController : Controller
    {
        private Hotel_DREntities db = new Hotel_DREntities();


        public ActionResult SveUloge()
        {
            return View(db.Ulogas.ToList());
        }




        public ActionResult NovaUloga()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NovaUloga(Uloga uloga)
        {
            if (ModelState.IsValid)
            {
                db.Ulogas.Add(uloga);
                db.SaveChanges();
                return RedirectToAction("SveUloge");
            }

            return View(uloga);
        }


        public ActionResult Izmeni(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uloga uloga = db.Ulogas.Find(id);
            if (uloga == null)
            {
                return HttpNotFound();
            }
            return View(uloga);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Izmeni(Uloga uloga)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uloga).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SveUloge");
            }
            return View(uloga);
        }

        // GET: Ulogas/Delete/5
        public ActionResult Obrisi(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uloga uloga = db.Ulogas.Find(id);
            if (uloga == null)
            {
                return HttpNotFound();
            }
            return View(uloga);
        }

        // POST: Ulogas/Delete/5
        [HttpPost, ActionName("Obrisi")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uloga uloga = db.Ulogas.Find(id);
            db.Ulogas.Remove(uloga);
            db.SaveChanges();
            return RedirectToAction("SveUloge");
        }



        public ActionResult SviStatusi()
        {
            return View(db.StatusSobes.ToList());
        }



        public ActionResult NoviStatus()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NoviStatus(StatusSobe statusSobe)
        {
            if (ModelState.IsValid)
            {
                db.StatusSobes.Add(statusSobe);
                db.SaveChanges();
                return RedirectToAction("SviStatusi");
            }

            return View(statusSobe);
        }


        public ActionResult IzmeniStatus(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StatusSobe statusSobe = db.StatusSobes.Find(id);
            if (statusSobe == null)
            {
                return HttpNotFound();
            }
            return View(statusSobe);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult IzmeniStatus(StatusSobe statusSobe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(statusSobe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SviStatusi");
            }
            return View(statusSobe);
        }

        
        public ActionResult ObrisiStatus(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StatusSobe statusSobe = db.StatusSobes.Find(id);
            if (statusSobe == null)
            {
                return HttpNotFound();
            }
            return View(statusSobe);
        }


        [HttpPost, ActionName("ObrisiStatus")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteSasvim(int id)
        {
            StatusSobe statusSobe = db.StatusSobes.Find(id);
            db.StatusSobes.Remove(statusSobe);
            db.SaveChanges();
            return RedirectToAction("SviStatusi");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projekat_Hotel/Controllers/Admin/GostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projekat_Hotel.Models;

namespace Projekat_Hotel.Controllers.Admin
{
    [Authorize]
    public class GostController : Controller
    {
        private Hotel_DREntities db = new Hotel_DREntities();

        [Authorize(Roles = "Admin, Menadžer")]
        public ActionResult SviGosti()
        {
            var danas = DateTime.Now;

            var sviGosti = (from   r in db.Rezervacijas
                            where (DateTime.Compare(r.Check_In ,danas)<= 0 && DateTime.Compare(r.Check_Out, danas) >=0) select r).ToList();
           
            
            return View(sviGosti);
        }

        [Authorize(Roles = "Admin, Menadžer")]
        public ActionResult BazaGostiju()
        {
           
        var bazaGostiju = db.Gosts.ToList();
            return View(bazaGostiju);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult IzmeniGosta(string id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
               return Content("Hi there! ID");
            }
           
            Gost gost = (from g in db.Gosts where g.GostID.Trim() == id select g).FirstOrDefault();
            if (gost == null)
            {
                //  return HttpNotFound();
                return Content("Hi there! GOST");
            }
            return View(gost);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult IzmeniGosta(Gost gost)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("BazaGostiju");
            }
            return View(gost);
        }


        [Authorize(Roles = "Admin")]
        public ActionResult ObrisiGosta(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gost gost = db.Gosts.Find(id);
            if (gost == null)
            {
                return HttpNotFound();
            }
            return View(gost);
        }


       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projekat_Hotel/Controllers/Admin/RacunController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projekat_Hotel.Models;

namespace Projekat_Hotel.Controllers
{
    [Authorize]
    public class RacunController : Controller
    {
        private Hotel_DREntities db = new Hotel_DREntities();
        // GET:
        public ActionResult SviRacuni()
        {
            var racuns = db.Racuns.Include(r => r.Rezervacija);
            return View("SviRacuni", racuns.ToList());
        }


        public ActionResult Detalji(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Racun racun = db.Racuns.Find(id);
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // Pravimo select listu načina plaćanja i šaljemo na View
        public ActionResult NoviRacun(int? id)
        {

            var selectList = new SelectList(
            new List<SelectListItem>
               {
                new SelectListItem {Text = "Gotovina", Value = "Gotovina"},
                new SelectListItem {Text = "Kartica", Value = "Kartica"},
                 new SelectListItem {Text = "Čekovi", Value = "Čekovi"},
               }, "Value", "Text");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            
            Racun racun = new Racun();

            if (racun == null)
            {
                return HttpNotFound();
            }
            racun.RezervacijaID = (int)id;
            ViewBag.nacinPlacanja = selectList;
            // ViewBag.RezervacijaID = new SelectList(zauzeteSobeRez, "RezervacijaID", "RezervacijaID");

            return View(racun);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NoviRacun(Racun racun)
        {

            var selectList = new SelectList(
            new List<SelectListItem>
               {
                new SelectListItem {Text = "Gotovina", Value = "Gotovina"},
                new SelectListItem {Text = "Kartica", Value = "Kartica"},
                 new SelectListItem {Text = "Čekovi", Value = "Čekovi"},
               }, "Value", "Text");
            ViewBag.nacinPlacanja = selectList;
            ViewBag.RezervacijaID = new SelectList(db.Rezervacijas, "RezervacijaID", "RezervacijaID");

            if (ModelState.IsValid)
            {
                Rezervacija rezervacijaKojaSeBrise = (from re in db.Rezervacijas where re.RezervacijaID == racun.RezervacijaID select re).Single();
                Soba sobaKojaSeOslobadja = (from s in db.Sobas where s.SobaID == rezervacijaKojaSeBrise.SobaID select s).Single();
                sobaKojaSeOslobadja.StatusID = 1004;
                // zauzeteSobeRez.Remove(rezervacijaKojaSeBrise);

                Racun r = new Racun();

                r.RezervacijaID = racun.RezervacijaID;
                if (racun.NacinPlacanja != null)
                {
                    try
                    {
                        r.NacinPlacanja = racun.NacinPlacanja;
                    }
                    catch (InvalidOperationException)
                    {
                        ViewBag.RezervacijaID = new SelectList(db.Rezervacijas, "RezervacijaID", "GostID", racun.RezervacijaID);
                        return View();
                    }
                }
                else
                {

                    return View();
                }

                r.Iznos = (double)rezervacijaKojaSeBrise.Cena;
                db.Racuns.Add(r);

                db.SaveChanges();
                int t = r.RacunID;
                return RedirectToAction("Detalji", new { @id = t });
                //return RedirectToAction("Index");
            }

            ViewBag.RezervacijaID = new SelectList(db.Rezervacijas, "RezervacijaID", "GostID", racun.RezervacijaID);
            return View("SviRacuni");


        }
        [Authorize(Roles = "Admin, Menadžer")]
        public ActionResult Storno(int? id)
        {
            //  int id =r.RacunID;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Racun racun = db.Racuns.Find(id);
            if (racun == null)
            {
                return HttpNotFound();
            }

            try
            {
                racun.Storno = "STORNO";
                db.SaveChanges();

            }
            catch (NullReferenceException e) { }
            return View("Storno");


        }


        public ActionResult Izmeni(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Racun racun = db.Racuns.Find(id);
            if (racun == null)
            {
                return HttpNotFound();
            }
            ViewBag.RezervacijaID = new SelectList(db.Rezervacijas, "RezervacijaID", "RezervacijaID", racun.RezervacijaID);
            return View(racun);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Izmeni([Bind(Include = "RacunID,RezervacijaID,NacinPlacanja,Iznos")] Racun racun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(racun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("SviRacuni");
            }
            ViewBag.RezervacijaID = new SelectList(db.Rezervacijas, "RezervacijaID", "GostID", racun.RezervacijaID);
            return View(racun);
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projekat_Hotel/Controllers/Admin/SobasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projekat_Hotel.Models;

namespace Projekat_Hotel.Controllers.Admin
{
    [Authorize]
    public class SobasController : Controller
    {
        private Hotel_DREntities db = new Hotel_DREntities();

        
        public ActionResult Index()
        {
            var sobas = db.Sobas.Include(s => s.StatusSobe);
            return View(sobas.ToList());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soba soba = db.Sobas.Find(id);
            if (soba == null)
            {
                return HttpNotFound();
            }
            ViewBag.StatusID = new SelectList(db.StatusSobes, "StatusID", "NazivStatusa", soba.StatusID);
            return View(soba);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Soba soba)
        {
            if (ModelState.IsValid)
            {
                db.Entry(soba).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StatusID = new SelectList(db.StatusSobes, "StatusID", "NazivStatusa", soba.StatusID);
            return View(soba);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projekat_Hotel/Views/Shared/_Layout(stari).cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Madrigal</title>
    <link rel="shortcut icon" href="~/images/ico.ico">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <a style="display: scroll;position:fixed;top:5px;left:35px;z-index: 1200;" href="../Home/Index" title="Pocetna stranica"><img src="~/images/MM3.png" /></a>

    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>*@
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">

                @Html.ActionLink("Madrigal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @if (Session["UserId"] != null)
                {
                    var uloga = Session["Privilegije"].ToString();
                    if (uloga == "1")
                    {
                        <ul class="nav navbar-nav ">
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Zaposleni", "SviRadnici", "Radnik")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Sobe", "Index", "Sobas")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Rezervacije", "SveRezervacije", "Rezervacija")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Gosti", "SviGosti", "Gost")
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Usluge", "SveUsluge", "Usluga")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Racuni", "SviRacuni", "Racun")
                            </li>
                        </ul>
                    }
                    else if (uloga == "2")
                    {
                        <ul class="nav navbar-nav ">
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Zaposleni", "SviZaposleni", "Manager")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Sobe", "SveSobe", "Manager")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Gosti", "SviGosti", "Manager")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Računi", "Sviracuni", "Manager")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Rezervacije", "Index", "Rezervacije")
                            </li>

                        </ul>
                    }
                    else if (uloga == "3")
                    {
                        <ul class="nav navbar-nav ">
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Zaposleni", "SviZaposleni", "Recepcija")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Sobe", "SveSobe", "Recepcija")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Usluge", "SviGosti", "Recepcija")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Računi", "SviRacuni", "Recepcija")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Rezervacije", "Index", "Recepcija")
                            </li>
                        </ul>
                    }
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item nav-link navbar-right">
                            <label style="color: white"> @Session["Ime"]</label> @Html.ActionLink("Logout", "Logout", "Login")
                        </li>
                    </ul>

                }
                else
                {

                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item nav-link navbar-right">
                            @Html.ActionLink("Login", "Index", "Login")
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ivanov, Bojanov i Pavlov završni rad</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Projekat_Hotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Madrigal</title>
    <link rel="shortcut icon" href="~/images/ico.ico">

    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@

    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <a style="display: inline; position:fixed;top:5px;left:35px;z-index: 1200;" href="../Home/Index" title="Pocetna stranica"><img src="~/images/MM33.png" /></a>


    <nav class="navbar navbar-inverse" id="navnav">
        <div class="container">
            <div class="navbar-header">

                @Html.ActionLink("Madrigal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @if (Session["UserId"] != null)
                {
                    var uloga = Session["Privilegije"].ToString();
                    if (uloga == "1")
                    {
                <ul class="nav navbar-nav ">
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Zaposleni", "SviRadnici", "Radnik")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Uloge", "SveUloge", "Alati")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Sobe", "Index", "Sobas")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Statusi soba", "SviStatusi", "Alati")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Rezervacije", "SveRezervacije", "Rezervacija")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Gosti", "SviGosti", "Gost")
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Usluge", "SveUsluge", "Usluga")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Racuni", "SviRacuni", "Racun")
                    </li>
                </ul>
                    }
                    else if (uloga == "2")
                    {
                        <ul class="nav navbar-nav ">
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Zaposleni", "SviZaposleni", "Manager")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Sobe", "SveSobe", "Manager")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Gosti", "SviGosti", "Gost")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Računi", "SviRacuni", "Manager")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Rezervacije", "SveRezervacije", "Rezervacija")
                            </li>

                        </ul>
                    }
                    else if (uloga == "3")
                    {
                        <ul class="nav navbar-nav ">

                            <li class="nav-item nav-link">
                                @Html.ActionLink("Sobe", "SveSobe", "Recepcija")
                            </li>
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Gosti", "SviGosti", "Recepcija")
                            </li>
                            @*<li class="nav-item nav-link">
                                @Html.ActionLink("Izdavanje računa", "NoviRacun", "Racun")
                            </li>*@
                            <li class="nav-item nav-link">
                                @Html.ActionLink("Rezervacije", "SveRezervacije", "Rezervacija")
                            </li>
                        </ul>
                    }
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item nav-link navbar-right">
                            @*<label style="color: white"> @Session["Ime"]</label>*@ @Html.ActionLink("Logout", "Logout", "Login")
                        </li>
                    </ul>

                }
                else
                {

                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item nav-link navbar-right">
                            @Html.ActionLink("Login", "Index", "Login")
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bojanov i Pavlov završni rad</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
    @*<script src="~/Scripts/jquery-3.3.1.min.js"></script>*@
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>